# Generated by Django 4.1.5 on 2023-03-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='covers',
            field=models.ImageField(default=1, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
