# Generated by Django 4.1.5 on 2023-03-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'گتاب', 'verbose_name_plural': 'کنابها'},
        ),
    ]
