# Generated by Django 4.1.5 on 2023-04-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='authority',
            new_name='zarinpal_authority',
        ),
    ]
